import type { ThemeConfig, ThemeId } from './types';

export const ICE: ThemeConfig = {
  id: 'ice',
  name: 'Buz Pateni',
  tagline: 'Donmuş göl uyanırken uzun, sessiz kavisler çiz.',
  emoji: '⛸️',
  control: 'thrust',
  collectibleName: 'yıldız',
  obstacleName: 'buz çatlağı',
  physics: {
    maxSpeed: 340,
    accel: 620,
    friction: 0.35,
    grip: 2.2,
    turnRate: 7,
    brakeFriction: 2.4,
    brakeGrip: 0.6,
    gravity: 1500,
  },
  palette: {
    washTop: '#f4fbfe',
    washBottom: '#a9c6dc',
    ground: '#d9eaf4',
    groundLight: '#eef7fc',
    groundShade: '#a8c6dd',
    contour: 'rgba(255, 255, 255, 0.5)',
    faceLit: '#f4f9ff',
    faceDark: '#9cbbd7',
    shadow: 'rgba(88, 124, 164, 0.20)',
    glow: '#ffd48a',
    ink: '#37536f',
    body: '#3d5f80',
    bodyAccent: '#f2a2b0',
    ribbon: 'rgba(255, 255, 255, 0.9)',
    haze: 'rgba(255, 214, 170, 0.16)',
    ui: '#5b8fc9',
    uiSoft: '#a8d4ee',
  },
  abilities: {
    doubleTap: {
      kind: 'hop',
      label: 'Axel',
      hint: 'Çift dokun',
      cooldown: 0.7,
      duration: 0,
      power: 620,
      style: 25,
    },
    swipe: {
      kind: 'dash',
      label: 'Atılım',
      hint: 'Kaydır',
      cooldown: 1.6,
      duration: 0,
      power: 420,
      style: 10,
    },
    hold: {
      kind: 'brake',
      label: 'Kızak',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const SKATE: ThemeConfig = {
  id: 'skate',
  name: 'Kaykay',
  tagline: 'Alacakaranlıkta beton ve uzun gölgeler. Ritmi bozma.',
  emoji: '🛹',
  control: 'thrust',
  collectibleName: 'kaset',
  obstacleName: 'beton blok',
  physics: {
    maxSpeed: 380,
    accel: 900,
    friction: 0.9,
    grip: 6,
    turnRate: 9,
    brakeFriction: 3.6,
    brakeGrip: 1.4,
    gravity: 1750,
  },
  palette: {
    washTop: '#cba79b',
    washBottom: '#553b52',
    ground: '#a87f80',
    groundLight: '#cba79b',
    groundShade: '#75566a',
    contour: 'rgba(255, 225, 205, 0.18)',
    faceLit: '#f3d5b2',
    faceDark: '#7b5865',
    shadow: 'rgba(48, 26, 38, 0.28)',
    glow: '#7fe3d2',
    ink: '#2e1d2a',
    body: '#f5e2c2',
    bodyAccent: '#e2725b',
    ribbon: 'rgba(255, 186, 148, 0.75)',
    haze: 'rgba(255, 160, 110, 0.18)',
    ui: '#e8896a',
    uiSoft: '#f3c9a8',
  },
  abilities: {
    doubleTap: {
      kind: 'hop',
      label: 'Ollie',
      hint: 'Çift dokun',
      cooldown: 0.55,
      duration: 0,
      power: 700,
      style: 30,
    },
    swipe: {
      kind: 'dash',
      label: 'Kickflip',
      hint: 'Kaydır',
      cooldown: 1.4,
      duration: 0,
      power: 380,
      style: 20,
    },
    hold: {
      kind: 'brake',
      label: 'Powerslide',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const SPACE: ThemeConfig = {
  id: 'space',
  name: 'Uzay Gemisi',
  tagline: 'Yıldız denizinde sürtünme yok; yalnızca atalet ve sen.',
  emoji: '🚀',
  control: 'thrust',
  collectibleName: 'kristal',
  obstacleName: 'asteroit',
  physics: {
    maxSpeed: 460,
    accel: 700,
    friction: 0.12,
    grip: 0.45,
    turnRate: 6,
    brakeFriction: 2.2,
    brakeGrip: 2.2,
    gravity: 1400,
  },
  palette: {
    washTop: '#2b2159',
    washBottom: '#120d29',
    ground: '#221a44',
    groundLight: '#352a68',
    groundShade: '#15102e',
    contour: 'rgba(170, 190, 255, 0.14)',
    faceLit: '#4f3f88',
    faceDark: '#221a48',
    shadow: 'rgba(5, 4, 15, 0.42)',
    glow: '#8fe8ff',
    ink: '#0d0a1e',
    body: '#f0ecff',
    bodyAccent: '#ffb27b',
    ribbon: 'rgba(150, 120, 255, 0.75)',
    haze: 'rgba(120, 90, 255, 0.16)',
    ui: '#9b7bff',
    uiSoft: '#8fe8ff',
  },
  abilities: {
    doubleTap: {
      kind: 'boost',
      label: 'Ateşleme',
      hint: 'Çift dokun',
      cooldown: 2.2,
      duration: 1.4,
      power: 1.85,
      style: 15,
    },
    swipe: {
      kind: 'dash',
      label: 'Yan İtki',
      hint: 'Kaydır',
      cooldown: 1.1,
      duration: 0,
      power: 460,
      style: 10,
    },
    hold: {
      kind: 'shield',
      label: 'Kalkan',
      hint: 'Basılı tut',
      cooldown: 3,
      duration: 1.8,
      power: 1,
      style: 0,
    },
  },
};

export const RALLY: ThemeConfig = {
  id: 'rally',
  name: 'Ralli',
  tagline: 'Altın kumullarda toz bırak, kendi gölgenle yarış.',
  emoji: '🏁',
  control: 'steer',
  collectibleName: 'bayrak',
  obstacleName: 'kaya',
  physics: {
    maxSpeed: 430,
    accel: 780,
    friction: 1.1,
    grip: 5.5,
    turnRate: 2.7,
    brakeFriction: 1.6,
    brakeGrip: 0.55,
    gravity: 1600,
  },
  palette: {
    washTop: '#f3cd85',
    washBottom: '#c07f3a',
    ground: '#dda85a',
    groundLight: '#f2cd84',
    groundShade: '#bb8040',
    contour: 'rgba(255, 240, 205, 0.30)',
    faceLit: '#f7dba6',
    faceDark: '#b0713a',
    shadow: 'rgba(118, 60, 20, 0.26)',
    glow: '#fff2cd',
    ink: '#5c3411',
    body: '#d24f3c',
    bodyAccent: '#f7e6c8',
    ribbon: 'rgba(255, 228, 175, 0.8)',
    haze: 'rgba(255, 190, 110, 0.15)',
    ui: '#e09a3c',
    uiSoft: '#f6d9a2',
  },
  abilities: {
    doubleTap: {
      kind: 'boost',
      label: 'Nitro',
      hint: 'Çift dokun',
      cooldown: 2.4,
      duration: 1.5,
      power: 1.75,
      style: 15,
    },
    swipe: {
      kind: 'hop',
      label: 'Sıçrama',
      hint: 'Kaydır',
      cooldown: 1.5,
      duration: 0,
      power: 560,
      style: 20,
    },
    hold: {
      kind: 'brake',
      label: 'El Freni',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const THEMES: Record<ThemeId, ThemeConfig> = {
  ice: ICE,
  skate: SKATE,
  space: SPACE,
  rally: RALLY,
};

export const THEME_LIST: ThemeConfig[] = [ICE, SKATE, SPACE, RALLY];
