import type { ThemeConfig, ThemeId } from './types';

export const ICE: ThemeConfig = {
  id: 'ice',
  name: 'Buz Pateni',
  tagline: 'Kayan, savrulan, zarif. Frenlemek yok, planlamak var.',
  emoji: '⛸️',
  control: 'thrust',
  collectibleName: 'yıldız',
  obstacleName: 'buz çatlağı',
  physics: {
    maxSpeed: 340,
    accel: 620,
    friction: 0.35,
    grip: 2.2,
    turnRate: 7,
    brakeFriction: 2.4,
    brakeGrip: 0.6,
    gravity: 1500,
  },
  palette: {
    floor: '#dff1fb',
    floorAlt: '#d3ecfa',
    grid: 'rgba(120, 176, 214, 0.35)',
    decal: 'rgba(255, 255, 255, 0.75)',
    fog: 'rgba(210, 238, 255, 0.55)',
    accent: '#3aa0ff',
    accent2: '#8ee3ff',
    body: '#1b3a5c',
    bodyAlt: '#f2f8ff',
    trail: 'rgba(255, 255, 255, 0.85)',
    collectible: '#ffd23f',
    obstacle: '#6d8aa5',
    obstacleAlt: '#9fb9cf',
    boostPad: '#4de1c1',
  },
  abilities: {
    doubleTap: {
      kind: 'hop',
      label: 'Axel',
      hint: 'Çift dokun',
      cooldown: 0.7,
      duration: 0,
      power: 620,
      style: 25,
    },
    swipe: {
      kind: 'dash',
      label: 'Atılım',
      hint: 'Kaydır',
      cooldown: 1.6,
      duration: 0,
      power: 420,
      style: 10,
    },
    hold: {
      kind: 'brake',
      label: 'Kızak',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const SKATE: ThemeConfig = {
  id: 'skate',
  name: 'Kaykay',
  tagline: 'Sert dönüşler, yüksek ollie, kombo peşinde koş.',
  emoji: '🛹',
  control: 'thrust',
  collectibleName: 'kaset',
  obstacleName: 'beton blok',
  physics: {
    maxSpeed: 380,
    accel: 900,
    friction: 0.9,
    grip: 6,
    turnRate: 9,
    brakeFriction: 3.6,
    brakeGrip: 1.4,
    gravity: 1750,
  },
  palette: {
    floor: '#3b3f4a',
    floorAlt: '#33373f',
    grid: 'rgba(255, 255, 255, 0.06)',
    decal: 'rgba(255, 214, 102, 0.35)',
    fog: 'rgba(24, 26, 32, 0.35)',
    accent: '#ff7a45',
    accent2: '#ffd166',
    body: '#ffd166',
    bodyAlt: '#20232b',
    trail: 'rgba(255, 122, 69, 0.6)',
    collectible: '#4dd4ff',
    obstacle: '#8a8f9c',
    obstacleAlt: '#6a6f7c',
    boostPad: '#c4ff4d',
  },
  abilities: {
    doubleTap: {
      kind: 'hop',
      label: 'Ollie',
      hint: 'Çift dokun',
      cooldown: 0.55,
      duration: 0,
      power: 700,
      style: 30,
    },
    swipe: {
      kind: 'dash',
      label: 'Kickflip',
      hint: 'Kaydır',
      cooldown: 1.4,
      duration: 0,
      power: 380,
      style: 20,
    },
    hold: {
      kind: 'brake',
      label: 'Powerslide',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const SPACE: ThemeConfig = {
  id: 'space',
  name: 'Uzay Gemisi',
  tagline: 'Sürtünme yok. İttiğin yöne sonsuza kadar gidersin.',
  emoji: '🚀',
  control: 'thrust',
  collectibleName: 'kristal',
  obstacleName: 'asteroit',
  physics: {
    maxSpeed: 460,
    accel: 700,
    friction: 0.12,
    grip: 0.45,
    turnRate: 6,
    brakeFriction: 2.2,
    brakeGrip: 2.2,
    gravity: 1400,
  },
  palette: {
    floor: '#0b1020',
    floorAlt: '#0e1530',
    grid: 'rgba(120, 150, 255, 0.12)',
    decal: 'rgba(180, 200, 255, 0.5)',
    fog: 'rgba(10, 14, 32, 0.5)',
    accent: '#7c5cff',
    accent2: '#38e8ff',
    body: '#e6ecff',
    bodyAlt: '#3b2f7a',
    trail: 'rgba(124, 92, 255, 0.6)',
    collectible: '#38e8ff',
    obstacle: '#5b6480',
    obstacleAlt: '#3d445c',
    boostPad: '#ff5cc8',
  },
  abilities: {
    doubleTap: {
      kind: 'boost',
      label: 'Ateşleme',
      hint: 'Çift dokun',
      cooldown: 2.2,
      duration: 1.4,
      power: 1.85,
      style: 15,
    },
    swipe: {
      kind: 'dash',
      label: 'Yan İtki',
      hint: 'Kaydır',
      cooldown: 1.1,
      duration: 0,
      power: 460,
      style: 10,
    },
    hold: {
      kind: 'shield',
      label: 'Kalkan',
      hint: 'Basılı tut',
      cooldown: 3,
      duration: 1.8,
      power: 1,
      style: 0,
    },
  },
};

export const RALLY: ThemeConfig = {
  id: 'rally',
  name: 'Ralli',
  tagline: 'Gaz, direksiyon, el freni. Virajı savurarak al.',
  emoji: '🏁',
  control: 'steer',
  collectibleName: 'bayrak',
  obstacleName: 'kaya',
  physics: {
    maxSpeed: 430,
    accel: 780,
    friction: 1.1,
    grip: 5.5,
    turnRate: 2.7,
    brakeFriction: 1.6,
    brakeGrip: 0.55,
    gravity: 1600,
  },
  palette: {
    floor: '#7a5c3a',
    floorAlt: '#735639',
    grid: 'rgba(0, 0, 0, 0.10)',
    decal: 'rgba(60, 42, 24, 0.45)',
    fog: 'rgba(120, 96, 60, 0.35)',
    accent: '#ffb703',
    accent2: '#e63946',
    body: '#e63946',
    bodyAlt: '#2b2118',
    trail: 'rgba(120, 96, 60, 0.7)',
    collectible: '#f1faee',
    obstacle: '#6f6357',
    obstacleAlt: '#544a41',
    boostPad: '#ffb703',
  },
  abilities: {
    doubleTap: {
      kind: 'boost',
      label: 'Nitro',
      hint: 'Çift dokun',
      cooldown: 2.4,
      duration: 1.5,
      power: 1.75,
      style: 15,
    },
    swipe: {
      kind: 'hop',
      label: 'Sıçrama',
      hint: 'Kaydır',
      cooldown: 1.5,
      duration: 0,
      power: 560,
      style: 20,
    },
    hold: {
      kind: 'brake',
      label: 'El Freni',
      hint: 'Basılı tut',
      cooldown: 0,
      duration: 0,
      power: 1,
      style: 0,
    },
  },
};

export const THEMES: Record<ThemeId, ThemeConfig> = {
  ice: ICE,
  skate: SKATE,
  space: SPACE,
  rally: RALLY,
};

export const THEME_LIST: ThemeConfig[] = [ICE, SKATE, SPACE, RALLY];
